### PR TITLE
Update to JSS v7.1.2 and jss-preset-default v2.0.0

### PR DESCRIPTION
**Pull request by kohlmannj**
I had experienced some issues when linking the latest version of JSS in a different repo which was also using aphrodite-jss. Hence, I've taken a moment to update several dependencies, including JSS, jss-preset-default, and a few of the devDependencies.

### CODE REVIEW

**Comment by kof** [comment]
Looks good

**Comment by kof** [comment]
merged

**Comment by kof** [comment]
published

**Comment by kohlmannj** [comment]
@kof I'm not seeing v1.1.0 on the NPM public registry:

<details><summary>Output of `npm list aphrodite-jss`</summary>

```bash
$ npm info aphrodite-jss
 
{ name: 'aphrodite-jss',
  description: 'Aphrodite-like API on top of JSS.',
  'dist-tags': { latest: '1.0.3' },
  versions: [ '1.0.1', '1.0.2', '1.0.3' ],
  maintainers: [ 'kof <oleg008@gmail.com>' ],
  time: 
   { modified: '2017-04-03T08:28:25.368Z',
     created: '2017-03-10T15:51:35.327Z',
     '1.0.1': '2017-03-10T15:51:35.327Z',
     '1.0.2': '2017-03-10T15:53:39.564Z',
     '1.0.3': '2017-04-03T08:28:25.368Z' },
  homepage: 'https://github.com/cssinjs/aphrodite-jss#readme',
  keywords: [ 'jss', 'cssinjs', 'css-in-js', 'aphrodite', 'react' ],
  repository: 
   { type: 'git',
     url: 'git+ssh://git@github.com/cssinjs/aphrodite-jss.git' },
  author: 'Oleg Slobodskoi <oleg008@gmail.com>',
  bugs: { url: 'https://github.com/cssinjs/aphrodite-jss/issues' },
  license: 'MIT',
  readmeFilename: 'readme.md',
  version: '1.0.3',
  scripts: 
   { all: 'npm run lint && npm run build',
     clean: 'rm -fr ./lib/*',
     build: 'npm run clean && npm run build:lib && npm run build:max && npm run build:min',
     'build:lib': 'cross-env babel src --out-dir lib',
     'build:max': 'cross-env NODE_ENV=development webpack src/index.js dist/aphrodite-jss.js',
     'build:min': 'cross-env NODE_ENV=production webpack src/index.js dist/aphrodite-jss.min.js',
     lint: 'eslint ./src ./tests ./benchmark ./*.js',
     'lint:staged': 'lint-staged',
     prepublish: 'npm run all' },
  main: './lib/index.js',
  engines: { node: '>=4.0.0' },
  devDependencies: 
   { 'babel-cli': '^6.5.1',
     'babel-core': '^6.5.1',
     'babel-eslint': '^7.1.1',
     'babel-loader': '^6.2.2',
     'babel-plugin-inline-version': '^1.0.2',
     'babel-plugin-transform-es3-member-expression-literals': '^6.8.0',
     'babel-preset-es2015': '^6.5.0',
     'babel-preset-stage-0': '^6.5.0',
     'es5-shim': '^4.3.1',
     eslint: '^3.0.1',
     'eslint-config-airbnb': '^9.0.1',
     'eslint-config-jss': '^3.0.0',
     'eslint-plugin-import': '^2.2.0',
     'eslint-plugin-jsx-a11y': '^1.0.2',
     'eslint-plugin-react': '^5.0.1',
     'json-loader': '^0.5.4',
     'lint-staged': '^3.2.2',
     'pre-commit': '^1.2.0',
     webpack: '^1.12.2' },
  dependencies: 
   { jss: '^6.0.1',
     'jss-preset-default': '^1.1.0',
     'murmurhash-js': '^1.0.0' },
  'lint-staged': { './src ./tests ./benchmark ./*.js': [ 'eslint', 'git add' ] },
  gitHead: 'd46119cb9e7519c378281f9c7ea5675baf9391ec',
  dist: 
   { shasum: '91888581ffe5f148c899d6036b17b5a99469372a',
     tarball: 'https://registry.npmjs.org/aphrodite-jss/-/aphrodite-jss-1.0.3.tgz' },
  directories: {} }
```
</details>

**Comment by kof** [comment]
after npm i linter broke

**Comment by kof** [comment]
fixing…

**Comment by kof** [comment]
now published

**Pull request merged**
